### PR TITLE
Seems to work fine with newer Aeson

### PR DESCRIPTION
**Pull request by bitemyapp**
Built fine anyway. There are no tests right?

### CODE REVIEW

**Comment by tibbe** [comment]
Would you mind having a look at the build failure? https://travis-ci.org/tibbe/ekg/jobs/67548295

**Comment by bitemyapp** [comment]
@tibbe oy. I'll kick it around it.

**Comment by bitemyapp** [comment]
@tibbe this error only occurred on 7.4.2 and I have no idea why Aeson broke that code only for that version of GHC. Do you need to maintain 7.4 compat going forward?

The error is about:

```
System/Remote/Json.hs:63:49:
    Couldn't match expected type `A.Object'
                with actual type `M.HashMap k0 v0'
    In the return type of a call of `M.insert'
    In the second argument of `($)', namely `M.insert str metric m'
    In the expression: A.Object $ M.insert str metric m
```

Well, fine, but why would that only be inconsistent in 7.4.2?

**Comment by tibbe** [comment]
We can probably drop 7.4 soon (I keep compat with the latest 3 major GHC releases). I have no idea what caused the failure. I haven't had time to look into it.

**Comment by bitemyapp** [comment]
@tibbe Proposed plan:

1. Bounce the TravisCI build (you'll need to do this, I don't think I can) and see if it passes this time (I suspect it won't based on the nature of the error)

2. If it does, fine. If not, I'll drop 7.4.2 from the `.travis.yml` and add 7.10. If it passes with those versions, we can proceed.

How does that sound?

**Comment by tibbe** [comment]
SGTM. I just kicked the travis bot.

**Comment by bitemyapp** [comment]
@tibbe Seems g2g now, I squashed the history.

**Pull request merged**
