### PR TITLE
stack support

### PR DESCRIPTION
**Pull request by yogsototh**
The same that was done for ekg-json.

This provide the ability to use stack to build the ekg package.
It would be great if you could put ekg and ekg-json to stackage.

If you don't want to put them yourself, I could put them for you and be the official stackage maintainer.

Best.

btw, thanks for ekg, it rocks!

### CODE REVIEW

**Comment by tibbe** [comment]
Stackage shouldn't require any upstream changes for it to work. It should just work with a .cabal file. Check with the Stackage maintainers.

**Comment by yogsototh** [comment]
Sorry I expressed myself wrongly. 

The current pull request was just here to create a working stack.yaml file. Just to help people using stack. 

Another unrelated demand was to put ekg and ekg-json in stackage. And if you don't want to publish these packages on stackage yourself, I proposed to to it for you.

**Comment by tibbe** [comment]
I believe these are on Stackage already, but I haven't checked. I prefer to not have Stackage specific files in my repo. Thanks!

**Comment by DanBurton** [comment]
> Stackage shouldn't require any upstream changes for it to work. It should just work with a .cabal file.

Correct. Whether a package repo has a `stack.yaml` file is completely orthogonal to whether that package is on stackage. This may seem surprising, but the stackage nightly and LTS build process don't even use stack!

**Pull request closed without merging**
